### ISSUE TITLE
did not have DP information and scaffolds not showing error

### ISSUE THREAD

**Issue by sandeshsth** [thlee/SNPhylo#5]
I ran snphylo and got the error below: did not have DP information and only recognizing chromosome

nphylo.sh -p 25 -v pcap-test1.vcf
Start to remove low quality data.

Warning: There were 1226148 SNP positions which did not have DP information.

Warning: 3444570 SNPs were passed without the read depth assessment because of the absence of the DP column.

1076957 low quality lines were removed.

SNPRelate: 0.9.18
Supported by Streaming SIMD Extensions 2 (SSE2).
Start snpgdsVCF2GDS ...
        Extracting bi-allelic and polymorhpic SNPs.
        Scanning ...
        file: snphylo.output.filtered.vcf
        content: 149191 rows x 16 columns
Fri Mar  6 14:05:59 2015        store sample id, snp id, position, and chromosome.
        start writing: 7 samples, 143461 SNPs ...
        file: snphylo.output.filtered.vcf
[1] 1
[1] 987
[1] 1967

[1] 140824
[1] 141808
[1] 142783
Fri Mar  6 14:07:02 2015        Done.
SNP pruning based on LD:
        Sliding window: 500000 basepairs, Inf SNPs
        |LD| threshold: 0.1
Removing 8305 non-autosomal SNPs
Removing 91959 SNPs (monomorphic, < MAF, or > missing rate)
Working space: 7 samples, 43197 SNPs
Chromosome 1: 0.15%, 26/16924
Chromosome 2: 0.14%, 10/7012
Chromosome 3: 0.12%, 11/9214
Chromosome 4: 0.16%, 7/4367
Chromosome 5: 0.14%, 17/12128
Chromosome 6: 0.16%, 9/5793
Chromosome 7: 0.27%, 5/1853
Chromosome 8: 0.11%, 11/9758
Chromosome 9: 0.17%, 10/5973
Chromosome 10: 0.12%, 22/17722
Chromosome 11: 0.14%, 13/9507
Chromosome 12: 0.12%, 8/6445
Chromosome 13: 0.21%, 10/4853
Chromosome 14: 0.15%, 8/5437
Chromosome 15: 0.15%, 7/4783
Chromosome 16: 0.15%, 11/7566
Chromosome 17: 0.18%, 7/3788
Chromosome 18: 0.20%, 4/2033
196 SNPs are selected in total.
Determine phylogenetic tree based on SNP data with a VCF, a HapMap, a Simple SNP or a GDS file

Version: 20140701

Usage:
        snphylo.sh -v VCF_file [-p Maximum_PLCS (5)] [-c Minimum_depth_of_coverage (5)]|-H HapMap_file [-p Maximum_PNSS (5)]|-s Simple_SNP_file [-p Maximum_PNSS (5)]|-d GDS_file [-l LD_threshold (0.1)] [-m MAF_threshold (0.1)] [-M Missing_rate (0.1)] [-o Outgroup_sample_name] [-P Prefix_of_output_files (snphylo.output)] [-b [-B The_number_of_bootstrap_samples (100)]] [-a The_number_of_the_last_autosome (22)] [-r] [-A] [-h]

Options:
        -A: Perform multiple alignment by MUSCLE
        -b: Perform (non-parametric) bootstrap analysis and generate a tree
        -h: Show help and exit
        -r: Skip the step removing low quality data (-p and -c option are ignored).

Acronyms:
        PLCS: The percent of Low Coverage Sample
        PNSS: The percent of Sample which has no SNP information
        LD: Linkage Disequilibrium
        MAF: Minor Allele Frequency

Simple SNP File Format:
        #Chrom  Pos     SampleID1       SampleID2       SampleID3       ...
        1       1000    A       A       T       ...
        1       1002    G       C       G       ...
        ...
        2       2000    G       C       G       ...
        2       2002    A       A       T       ...
        ...

Error: The length of sequence is too short (< 500 bp) to construct a tree!
Please restart this script with different parameter values (-l, -m and/or -M).

**Comment by ayangromano** [comment]
Hello,

I am also receiving the same error. I changed my -l to 0.5 so it is less stringent, than 0.1, but still received the same error. I wasn't sure what the -m and -M would do, so I didn't change those two parameters. 

Did you figure out how to overcome this and/or do you have any suggestions/tips?

Thanks!
Ashley

**Comment by thlee** [comment]
The SNPhylo uses the SNPs with ">= the MAF value" and "<= the Missing_rate value" only.
Thus, please try decrease the MAF value and/or increase the Missing_rate in order to solve the problem.
Thank you,

**Comment by ayangromano** [comment]
Thanks! I've tried decreasing the MAF value to various values and also increasing the Missing_Rate to various values. However, I am still receiving the error stating that my sequence is too short. I've also tried changing the LD_threshold and receive either "The length of sequence is too long" or "The length of sequence is too short". Do you have any other suggestions on what I can possibly do or insight into what might be stopping the script from constructing a tree?

**Comment by vignesh2008** [comment]
I got the same error. Is there any solution?. I have DP for all SNPs. I merged VCF files by GATK CombineVariants. 

=====
snphylo.sh -v GATKMergedLines.vcf.snphylo.vcf -m 0.1 -P GATKMergedLines_snphylo.Out
Start to remove low quality data.

Warning: There were 7288305 SNP positions which did not have DP information.

Warning: 107150425 SNPs were passed without the read depth assessment because of the absence of the DP column.

7288184 low quality lines were removed.

SNPRelate -- supported by Streaming SIMD Extensions 2 (SSE2)
Error in snpgdsVCF2GDS(vcf.file, gds.file, method = "biallelic.only",  :
  unused argument (option = snpgds.option)
Execution halted

======

**Comment by thlee** [comment]
A script, "generate_snp_sequence.R", was revised in order to solve the error.
Please download the file from the GitHub and overwrite the old file with the new file.

Sincerely,

**Comment by sbcrg** [comment]
Hi,
I get the same error: my version of "generate_snp_sequence.R" seems to have been modified on February 4th of this year. Is there a more recent version somewhere?

**Comment by sbcrg** [comment]
Hi again,
Could you please help me regarding this? Is my "generate_snp_sequence.R" the right version?
No matter how relaxed are my parameters (decreased  MAF and increase Missing_rate), I still get the "Error: There are too small number of SNP data in the file" error.
Now when I try to remove the quality filtering step (-r option), I get this error:
"Error: unexpected '<' in "<""
So I am sort of stuck.
Thanks a lot!

**Comment by edgarjavi** [comment]
Is your analysis with humans? I had the same error but I realized that I had 10K+ scaffolds so I had to use the flag -a and give the last value of the scaffold. That fixed it!
